# Generated by Django 5.1.5 on 2025-02-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
