# Generated by Django 5.1.5 on 2025-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_post_link_url_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='author_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
