# Generated by Django 5.1.5 on 2025-03-13 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_author_nickname_post_author_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
