# Generated by Django 5.1.5 on 2025-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
