# Generated by Django 5.1.5 on 2025-02-19 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('in_app', 'In-app only'), ('push_in_app', 'Push & In-app')], default='in_app', max_length=20)),
                ('notify_when_post_liked', models.BooleanField(default=False)),
                ('notify_when_commented', models.BooleanField(default=False)),
                ('notify_when_mentioned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
