# Generated by Django 5.1.5 on 2025-02-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='notify_when_commented',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='notify_when_mentioned',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='notify_when_post_liked',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='notification_categories',
            field=models.ManyToManyField(blank=True, to='settings_app.notificationcategory'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.notificationtype'),
        ),
    ]
