# Generated by Django 5.1.5 on 2025-03-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_notificationcategory_notificationtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='문의하는 사용자의 이메일', max_length=254)),
                ('title', models.CharField(help_text='문의 제목', max_length=255)),
                ('details', models.TextField(help_text='문의 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='문의 작성 시간')),
                ('is_resolved', models.BooleanField(default=False, help_text='처리 여부')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
