# Generated by Django 5.1.5 on 2025-04-07 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='notification_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.notificationtype'),
        ),
    ]
