# Generated by Django 5.1.5 on 2025-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_usersetting_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='notification_type',
            field=models.ManyToManyField(blank=True, to='settings_app.notificationtype'),
        ),
    ]
