# Generated by Django 5.1.5 on 2025-06-28 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='meeting_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'post_id', 'comment_id', 'meeting_id')},
        ),
    ]
