# Generated by Django 5.1.5 on 2025-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_alter_report_unique_together_report_meeting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='meetup_notification',
            field=models.BooleanField(default=True),
        ),
    ]
