# Generated by Django 5.1.5 on 2025-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_usersetting_meetup_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason_text',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
