# Generated by Django 5.1.5 on 2025-07-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_alter_report_reason_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='notification_type',
        ),
    ]
