# Generated by Django 5.1.5 on 2025-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_comment_id_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
