# Generated by Django 5.1.5 on 2025-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='board_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
