# Generated by Django 5.1.5 on 2025-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meetup_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
