# Generated by Django 5.1.5 on 2025-02-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='student_id',
            new_name='admission_year',
        ),
    ]
