# Generated by Django 5.1.5 on 2025-02-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_student_id_userprofile_admission_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_profile_complete',
        ),
    ]
