# Generated by Django 5.1.5 on 2025-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(blank=True, default='https://your-supabase-url.com/default_profile.png', max_length=500, null=True),
        ),
    ]
