# Generated by Django 5.1.5 on 2025-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_language_nationality_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduce',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
