# Generated by Django 5.1.5 on 2025-06-23 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_userprofile_introduce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('category_id', models.IntegerField(choices=[(0, 'Event'), (1, 'Academic')])),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rlg', models.CharField(choices=[('Seoul', 'Seoul'), ('Busan', 'Busan'), ('Daegu', 'Daegu'), ('Incheon', 'Incheon'), ('Gwangju', 'Gwangju'), ('Daejeon', 'Daejeon'), ('Ulsan', 'Ulsan'), ('Sejong', 'Sejong'), ('Gyeonggi', 'Gyeonggi'), ('Gangwon', 'Gangwon'), ('Chungbuk', 'Chungbuk'), ('Chungnam', 'Chungnam'), ('Jeonbuk', 'Jeonbuk'), ('Jeonnam', 'Jeonnam'), ('Gyeongbuk', 'Gyeongbuk'), ('Gyeongnam', 'Gyeongnam'), ('Jeju', 'Jeju')], max_length=20)),
                ('thumbnails', models.JSONField(default=list)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(to='account.language')),
                ('nationalities', models.ManyToManyField(to='account.nationality')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
