# Generated by Django 5.1.5 on 2025-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_userprofile_language_userprofile_languages'),
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='school_ids',
            field=models.ManyToManyField(blank=True, to='account.school'),
        ),
    ]
