# Generated by Django 5.1.5 on 2025-06-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_meeting_school_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_closed_manual',
            field=models.BooleanField(default=False),
        ),
    ]
