# Generated by Django 5.1.5 on 2025-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_meetingqna_meetingqnacomment_meetingsearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_all_languages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_all_nationalities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_all_schools',
            field=models.BooleanField(default=False),
        ),
    ]
